[package]
name = "internal-testing"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "1.3.3"
futures-util = { version = "0.3.31", features = ["sink"] }
tokio = { version = "1.43.0", features = ["rt", "rt-multi-thread", "macros", "io-util", "time"] }
webcontr.path = "../../webcontr"
